/*
 * @Author: bucai
 * @Date: 2021-03-21 21:20:08
 * @LastEditors: bucai<1450941858@qq.com>
 * @LastEditTime: 2022-03-12 09:41:22
 * @Description: 
 */
import {
  mdiCardsHeart, mdiArrowLeft,
  mdiEye, mdiMinus, mdiMessageProcessing,
  mdiArrowRight, mdiGithub,
  mdiWhiteBalanceSunny,
  mdiWeatherNight,
  mdiMessage,
  mdiBell,
  mdiMenu,
  mdiSinaWeibo,
  mdiTrashCan,
  mdiCloudUploadOutline,
  mdiImageSizeSelectActual,
  mdiPencil,
  mdiClose,
  mdiEarth,
  mdiAccount,
  mdiExitToApp,
  mdiArrowUpThick,
  mdiChevronUp,
  mdiYoutubeGaming,
  mdiCodeTags,
  mdiMicrosoftOnenote,
  mdiAccountSupervisorCircleOutline,
  mdiAllInclusive,
  mdiDotsHorizontal,
  mdiTimelineClock,
  mdiDotsVertical,
  mdiLinkVariant,
  mdiApps,
  mdiLink,
  mdiMessageText,
  mdiExclamation,
  mdiAlertCircleOutline,
  mdiMagnify
} from '@mdi/js'
import Vue from 'vue';

Vue.prototype.$icons = {
  'mdi-cards-heart': mdiCardsHeart,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-eye': mdiEye,
  'mdi-minus': mdiMinus,
  'mdi-message-processing': mdiMessageProcessing,
  'mdi-message': mdiMessage,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-github': mdiGithub,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-bell': mdiBell,
  'mdi-menu': mdiMenu,
  'mdi-sina-weibo': mdiSinaWeibo,
  'mdi-trash-can': mdiTrashCan,
  'mdi-cloud-upload-outline': mdiCloudUploadOutline,
  'mdi-image-size-select-actual': mdiImageSizeSelectActual,
  'mdi-pencil': mdiPencil,
  'mdi-close': mdiClose,
  'mdi-earth': mdiEarth,
  'mdi-account': mdiAccount,
  'mdi-exit-to-app': mdiExitToApp,
  'mdi-arrow-up-thick': mdiArrowUpThick,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-youtube-gaming': mdiYoutubeGaming,
  'mdi-code-tags': mdiCodeTags,
  'mdi-microsoft-onenote': mdiMicrosoftOnenote,
  'mdi-account-supervisor-circle-outline': mdiAccountSupervisorCircleOutline,
  'mdi-all-inclusive': mdiAllInclusive,
  'mdi-dots-horizontal': mdiDotsHorizontal,
  'mdi-timeline-clock': mdiTimelineClock,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-link': mdiLink,
  'mdi-message-text': mdiMessageText,
  'mdi-apps': mdiApps,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-magnify':mdiMagnify,
  'mdi-dots-vertical': mdiDotsVertical
};